---
- name: install httpie
  package:
    name: httpie
    state: latest

- name : install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    enabled: yes
  notify: restart HAProxy

- name: configure haproxy.conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
