---
- name: Install Httpie
  package:
    name: httpie
    state: latest

- name : Install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy at boot
  service:
    name: haproxy
    enabled: yes
  notify: restart HAProxy

- name: copy haproxy.cfg to /etc/haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
