---
- name: Install Apache and Tomcat
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - tomcat
    - httpd

- name: enable apache and tomcat at boot
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - tomcat
    - httpd
  notify: restart apache tomcat

- name: create /usr/share/tomcat/webapps/ROOT and /usr/share/tomcat/webapps/ansible directories
  file:
    path: /usr/share/tomcat/webapps/{{ item }}
    state: directory
  loop:
    - ROOT
    - ansible

- name: copy index.html to tomcat webapps/ansible and webapps/ROOT
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/{{ item }}/index.html
    mode: 0644
  loop:
    - ROOT
    - ansible 
