---
- name: Install Postgresql
  yum:
    name: postgresql-server
    state: latest

- name: enable postgresql at boot
  service:
    name: postgresql
    enabled: yes
  notify: restart postgresql

- name: check existing /var/lib/pgsql/data
  stat:
    path: /var/lib/pgsql/data
  register: p

- name: when existing /var/lib/pgsql/data, then initialize postgresql
  command: postgresql-setup initdb
  when: not p.stat.exists
  